site_name: OnBoarding Digital

theme:
  name: material
  language: pt-BR
  palette:
    scheme: slate
    primary: blue
    accent: light blue

nav:
  - Home: index.md
  - MVP: mvp.md
  - Requisitos: requisitos.md
  - Planejamento: planejamento-semanal.md
  - Reuniões: reunioes.md
  - Stacks: stacks-utilizadas.md