"""create initial tables

Revision ID: 80b27029bf5e
Revises: 
Create Date: 2026-05-31 20:36:55.710293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '80b27029bf5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acao_auditoria',
    sa.Column('nomeAcao', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('nomeAcao')
    )
    op.create_table('status_documento',
    sa.Column('nomeStatus', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('nomeStatus')
    )
    op.create_table('tipo_documento',
    sa.Column('nomeDoc', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('nomeDoc')
    )
    op.create_table('usuario',
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('idUsuario'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuario_idUsuario'), 'usuario', ['idUsuario'], unique=False)
    op.create_table('colaborador',
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('dataNascimento', sa.Date(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('cpf'),
    sa.UniqueConstraint('idUsuario')
    )
    op.create_table('rh',
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('matricula'),
    sa.UniqueConstraint('idUsuario')
    )
    op.create_table('telefone',
    sa.Column('numeroTelefone', sa.String(length=20), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.idUsuario'], ),
    sa.PrimaryKeyConstraint('numeroTelefone', 'idUsuario')
    )
    op.create_table('documento',
    sa.Column('idDoc', sa.Integer(), nullable=False),
    sa.Column('caminhoArquivo', sa.String(length=255), nullable=False),
    sa.Column('dataEnvio', sa.DateTime(), nullable=False),
    sa.Column('nomeArquivo', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('nomeDoc', sa.String(length=100), nullable=False),
    sa.Column('nomeStatus', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['cpf'], ['colaborador.cpf'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.idUsuario'], ),
    sa.ForeignKeyConstraint(['nomeDoc'], ['tipo_documento.nomeDoc'], ),
    sa.ForeignKeyConstraint(['nomeStatus'], ['status_documento.nomeStatus'], ),
    sa.PrimaryKeyConstraint('idDoc')
    )
    op.create_index(op.f('ix_documento_idDoc'), 'documento', ['idDoc'], unique=False)
    op.create_table('log_auditoria',
    sa.Column('idAuditoria', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('dataHora', sa.DateTime(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('idDoc', sa.Integer(), nullable=False),
    sa.Column('nomeAcao', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['idDoc'], ['documento.idDoc'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.idUsuario'], ),
    sa.ForeignKeyConstraint(['nomeAcao'], ['acao_auditoria.nomeAcao'], ),
    sa.PrimaryKeyConstraint('idAuditoria')
    )
    op.create_index(op.f('ix_log_auditoria_idAuditoria'), 'log_auditoria', ['idAuditoria'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_auditoria_idAuditoria'), table_name='log_auditoria')
    op.drop_table('log_auditoria')
    op.drop_index(op.f('ix_documento_idDoc'), table_name='documento')
    op.drop_table('documento')
    op.drop_table('telefone')
    op.drop_table('rh')
    op.drop_table('colaborador')
    op.drop_index(op.f('ix_usuario_idUsuario'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('tipo_documento')
    op.drop_table('status_documento')
    op.drop_table('acao_auditoria')
    # ### end Alembic commands ###
